### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by yob** [openvenues/ruby_postal#2]
Hi,

libpostal and this gem look really interesting. I notice that it's [not on rubygems.org yet](https://rubygems.org/search?utf8=%E2%9C%93&query=ruby_postal). I know I can add it to my Gemfile via a git reference, but are you also planning to release a version to rubygems.org?

**Comment by albarrentine** [comment]
Thanks! Just published: https://rubygems.org/gems/ruby_postal. Note that the libpostal C library has to be installed separately (currently via make install, packaging on the way).

**Comment by yob** [comment]
Thanks!
