### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by dkolath** [openvenues/ruby_postal#4]
Are there plans to bump the version soon? Encountered the following issue, and then noticed that it was fixed after the last version bump.

https://github.com/openvenues/ruby_postal/issues/1

**Comment by albarrentine** [comment]
Are you talking about the gem? That should include all the latest commits and be up-to-date. 

To answer your main question, yes. There's a huge update coming out of the main C repo (the merge of [parser-data](https://github.com/openvenues/libpostal/tree/parser-data)) in the relatively near future that will require version updates for all the bindings.

**Comment by daguar** [comment]
Howdy! It looks like the version actually does need a bump, as this fix (for #1 ) isn't included on what you get by RubyGems right now.

**Comment by albarrentine** [comment]
Ok, no worries. Pushed another version (0.3.1): https://rubygems.org/gems/ruby_postal

**Comment by daguar** [comment]
Thank you! I think it's okay to close this.
