### ISSUE TITLE
Wierd characters

### ISSUE THREAD

**Issue by chamnap** [openvenues/ruby_postal#5]
I have an address `47 Boulevard Gréber, Gatineau, QC J8T3P7, Canada`. 
After I parsed this address, the value returns back as: `[{:label=>:house_number, :value=>"47"}, {:label=>:road, :value=>"boulevard gre\xCC\x81ber"}, {:label=>:city, :value=>"gatineau"}, {:label=>:state, :value=>"qc"}, {:label=>:postcode, :value=>"j8t3p7"}, {:label=>:country, :value=>"canada"}]`.

`boulevard gre\xCC\x81ber` is not UTF-8. How to fix this?

**Comment by albarrentine** [comment]
That's just the form of [Unicode normalization](http://unicode.org/reports/tr15/) libpostal currently uses (NFD). In the next version of the libpostal C library it will use NFC, which does produce valid UTF-8.

In the meantime, in Ruby 2.2+ you can use [.unicode_normalize(:nfc)](https://ruby-doc.org/stdlib-2.2.1/libdoc/unicode_normalize/rdoc/String.html). Or try [this library](https://github.com/blackwinter/unicode).

**Comment by albarrentine** [comment]
Hey @chamnap, libpostal 1.0 has been released in master, as well as the corresponding gem. It uses NFC normalization, so no more weird characters. For Ruby we're also now doing and encode on the input to the C functions and a force_encoding on the way out, so hopefully won't have to worry too much about encoding with the new libpostal/ruby_postal gem.
